version: "3.8"

services:
  fpm:
    restart: always
    external_links:
      - infra-services-db-1:db
    build:
      context: ./app
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./app:/app:rw,cached
    ports:
      - "9000:9000"
    networks:
      - tools

  nginx-lobievents:
    container_name: nginx-lobievents
    build:
      context: ./app
      dockerfile: docker/nginx/Dockerfile-nginx
    restart: always
    links:
      - fpm
    depends_on:
      - fpm
    volumes:
      - ./app:/app:rw,cached
#      - /etc/letsencrypt:/etc/letsencrypt:ro
#      - /tmp/acme_challenge:/tmp/acme_challenge
    expose:
      - "8081"
#      - '443:443'
    networks:
      - tools
    environment:
      - VIRTUAL_HOST=resume.tlabs.digital
      - VIRTUAL_PORT=8081

volumes:
  db-data-lobievents: {}

networks:
    tools:
        name: infra-services_tools
