version: '3.8'

services:
  fpm:
    restart: always
    external_links:
      - infra-services-db-1:db
    build:
      context: ./app
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./app:/app:rw,cached
    ports:
      - "9002:9000"
    networks:
      - tools

  nginx-expense-report:
    container_name: nginx-expense-report
    build:
      context: ./app
      dockerfile: docker/nginx/Dockerfile-nginx
    restart: always
    links:
      - fpm
    depends_on:
      - fpm
    volumes:
      - ./app:/app:rw,cached
    ports:
      - "8082:80"
    networks:
      - tools

networks:
  tools:
    external: true
    name: infra-services_tools
