services:
    db:
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: toto44
        image: "mariadb:10.7.1"
        ports:
            - "3306:3306"
        volumes:
            - "./docker/shared/mysql:/var/lib/mysql"
        networks:
            - tools

    mailcatcher:
        container_name: mailcatcher
        restart: always
        image: stpaquet/alpinemailcatcher:latest
        networks:
            - tools
        environment:
            - MAIL_LIMIT=70
            - TIMEZONE=Europe/Paris
        ports:
            - '1080:1080'
            - '1025:1025'

    nginx-proxy:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
        networks:
            - tools

    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        ports:
            - '9003:9000'
        networks:
            - tools

    ngrok:
        image: wernight/ngrok
        container_name: ngrok
        restart: unless-stopped
        volumes:
            - ./ngrok/ngrok.yml:/home/ngrok/.ngrok2/ngrok.yml
        ports:
            - "4040:4040"
        command: ["ngrok", "http", "8083"]
        networks:
            - tools

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "8888:80"
        environment:
            - PMA_ARBITRARY=1
        networks:
            - tools

networks:
    tools:
        name: tools

volumes:
    portainer_data: {}
