version: "3.8"

services:
    db:
        environment:
            MYSQL_ROOT_PASSWORD: toto44
        image: "mariadb:10.7.1"
        networks:
            - tools
        ports:
            - "3306:3306"
        volumes:
            - "./docker/shared/mysql:/var/lib/mysql"

    mailcatcher:
        container_name: mailcatcher
        restart: always
        image: stpaquet/alpinemailcatcher:latest
        networks:
            - tools
        environment:
            - MAIL_LIMIT=70
            - TIMEZONE=Europe/Paris
        ports:
            - '1080:1080'
            - '1025:1025'

networks:
    tools:
