<?php

namespace ContainerUQMPz1Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAO2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XDAHA.P.App\Entity\AO' shared service.
     *
     * @return \App\Entity\AO
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.XDAHA.P": it needs an instance of "App\\Entity\\AO" but this type has been excluded in "config/services.yaml".');
    }
}
