vich_uploader:
    db_driver: orm

    mappings:
        ao_documents:
            uri_prefix: /uploads/ao_documents
            upload_destination: '%kernel.project_dir%/public/uploads/ao_documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer