version: '3.8'

services:
  fpm:
    restart: always
    external_links:
      - infra-services-db-1:db
    build:
      context: ./docker
      dockerfile: php-fpm/Dockerfile
    volumes:
      - .:/app:rw,cached
    ports:
      - "9001:9000"
    networks:
      - tools

  nginx-resume:
    container_name: nginx-resume
    build:
      context: ./docker
      dockerfile: nginx/Dockerfile-nginx
    restart: always
    links:
      - fpm
    depends_on:
      - fpm
    volumes:
      - .:/app:rw,cached
    ports:
      - "8080:80"
    networks:
      - tools

volumes:
  db-data-resume: {}

networks:
  tools:
      external: true
      name: infra-services_tools
