services:
  fpm:
    restart: always
    build:
      context: ./app
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./app:/app:rw,cached
      - /app/node_modules
      - /app/public/build
    ports:
      - "9007:9000"
    networks:
      - tools

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    restart: always
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - network.host=0.0.0.0
      - xpack.security.enabled=false # Désactive l'authentification
      - xpack.security.http.ssl.enabled=false # Désactive SSL
    ports:
      - "9200:9200"
      - "9300:9300" # Port de communication cluster
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -qE '\"status\":\"(green|yellow)\"'"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - tools


  nginx-bid:
    container_name: nginx-bid
    build:
      context: ./app
      dockerfile: docker/nginx/Dockerfile-nginx
    restart: always
    links:
      - fpm
    depends_on:
      - fpm
    volumes:
      - ./app:/app:rw,cached
      - ./app/public:/app/public:ro
    ports:
      - "8086:80"
    networks:
      - tools

volumes:
  db-data-bid: {}
  es_data: {}

networks:
  tools:
    external: true
    name: tools