<?php

namespace ContainerQdBfhpK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WQ9PkZ4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wQ9PkZ4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wQ9PkZ4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AOController::edit' => ['privates', '.service_locator.QrYvljr.App\\Controller\\AOController::edit()', 'getAOControllereditService', true],
            'App\\Controller\\AOController::submit' => ['privates', '.service_locator.XDAHA.P.App\\Controller\\AOController::submit()', 'getAOControllersubmitService', true],
            'App\\Controller\\AOController::detail' => ['privates', '.service_locator.QrYvljr.App\\Controller\\AOController::detail()', 'getAOControllerdetailService', true],
            'App\\Controller\\AOController::close' => ['privates', '.service_locator.QrYvljr.App\\Controller\\AOController::close()', 'getAOControllercloseService', true],
            'App\\Controller\\AOController::downloadPdf' => ['privates', '.service_locator.QrYvljr.App\\Controller\\AOController::downloadPdf()', 'getAOControllerdownloadPdfService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::index()', 'getLoginControllerindexService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.KAWHxDW.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AOController:edit' => ['privates', '.service_locator.QrYvljr.App\\Controller\\AOController::edit()', 'getAOControllereditService', true],
            'App\\Controller\\AOController:submit' => ['privates', '.service_locator.XDAHA.P.App\\Controller\\AOController::submit()', 'getAOControllersubmitService', true],
            'App\\Controller\\AOController:detail' => ['privates', '.service_locator.QrYvljr.App\\Controller\\AOController::detail()', 'getAOControllerdetailService', true],
            'App\\Controller\\AOController:close' => ['privates', '.service_locator.QrYvljr.App\\Controller\\AOController::close()', 'getAOControllercloseService', true],
            'App\\Controller\\AOController:downloadPdf' => ['privates', '.service_locator.QrYvljr.App\\Controller\\AOController::downloadPdf()', 'getAOControllerdownloadPdfService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::index()', 'getLoginControllerindexService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.KAWHxDW.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AOController::edit' => '?',
            'App\\Controller\\AOController::submit' => '?',
            'App\\Controller\\AOController::detail' => '?',
            'App\\Controller\\AOController::close' => '?',
            'App\\Controller\\AOController::downloadPdf' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AOController:edit' => '?',
            'App\\Controller\\AOController:submit' => '?',
            'App\\Controller\\AOController:detail' => '?',
            'App\\Controller\\AOController:close' => '?',
            'App\\Controller\\AOController:downloadPdf' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
        ]);
    }
}
