<?php

namespace ContainerQdBfhpK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAOControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QrYvljr.App\Controller\AOController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QrYvljr.App\\Controller\\AOController::edit()'] = ($container->privates['.service_locator.QrYvljr'] ?? $container->load('get_ServiceLocator_QrYvljrService'))->withContext('App\\Controller\\AOController::edit()', $container);
    }
}
