<?php

namespace ContainerQdBfhpK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAOControllersubmitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XDAHA.P.App\Controller\AOController::submit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XDAHA.P.App\\Controller\\AOController::submit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ao' => ['privates', '.errored..service_locator.XDAHA.P.App\\Entity\\AO', NULL, 'Cannot autowire service ".service_locator.XDAHA.P": it needs an instance of "App\\Entity\\AO" but this type has been excluded in "config/services.yaml".'],
            'docManager' => ['privates', 'App\\Service\\DocumentManager', 'getDocumentManagerService', true],
        ], [
            'ao' => 'App\\Entity\\AO',
            'docManager' => 'App\\Service\\DocumentManager',
        ]))->withContext('App\\Controller\\AOController::submit()', $container);
    }
}
