services:
  fpm:
    restart: always
    external_links:
      - infra-services-db-1:db
    build:
      context: ./app
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./app:/app:rw,cached
    ports:
      - "9005:9000"
    networks:
      - tools

  nginx-station:
    container_name: nginx-station
    build:
      context: ./app
      dockerfile: docker/nginx/Dockerfile-nginx
    restart: always
    links:
      - fpm
    depends_on:
      - fpm
    volumes:
      - ./app:/app:rw,cached
    ports:
      - "8084:80"
    networks:
      - tools

volumes:
  db-data-station: {}

networks:
    tools:
        external: true
        name: infra-services_tools
